# Generated by Django 4.1.7 on 2023-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_alter_restaurants_restaurant_pictures1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='closing_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='contact',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opening_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='restaurant_pictures5',
            field=models.ImageField(blank=True, upload_to='Restaurants'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='restaurant_pictures6',
            field=models.ImageField(blank=True, upload_to='Restaurants'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='restaurant_pictures7',
            field=models.ImageField(blank=True, upload_to='Restaurants'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='restaurant_pictures8',
            field=models.ImageField(blank=True, upload_to='Restaurants'),
        ),
    ]
