# Generated by Django 4.1.7 on 2023-03-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingMalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mall_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('mall_pictures1', models.ImageField(upload_to='media/ShoppingMalls')),
                ('mall_pictures2', models.ImageField(blank=True, upload_to='media/ShoppingMalls')),
                ('mall_pictures3', models.ImageField(blank=True, upload_to='media/ShoppingMalls')),
                ('mall_pictures4', models.ImageField(blank=True, upload_to='media/ShoppingMalls')),
            ],
            options={
                'verbose_name': 'Shopping Malls',
                'verbose_name_plural': 'Shopping Malls',
            },
        ),
    ]
