# Generated by Django 4.1.7 on 2023-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingMalls', '0002_alter_shoppingmalls_mall_pictures1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingmalls',
            name='closing_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='contact',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='shoppingmalls',
            name='opening_time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
