# Generated by Django 4.1.7 on 2023-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0002_alter_hotels_hotel_pictures1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='check_in_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hotels',
            name='check_out_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hotels',
            name='contact1',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='hotels',
            name='contact2',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='hotels',
            name='hotel_pictures5',
            field=models.ImageField(blank=True, upload_to='Hotels'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='hotel_pictures6',
            field=models.ImageField(blank=True, upload_to='Hotels'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='hotel_pictures7',
            field=models.ImageField(blank=True, upload_to='Hotels'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='hotel_pictures8',
            field=models.ImageField(blank=True, upload_to='Hotels'),
        ),
    ]
