# Generated by Django 4.1.2 on 2023-04-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0004_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='hotel',
        ),
    ]
