# Generated by Django 4.1.2 on 2023-04-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0006_visitlater'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitlater',
            options={'verbose_name': 'VisitLater', 'verbose_name_plural': 'Visit Later'},
        ),
        migrations.AddField(
            model_name='visitlater',
            name='category',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
