# Generated by Django 4.1.2 on 2023-04-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0007_alter_visitlater_options_visitlater_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlater',
            name='category',
            field=models.CharField(default='Hotel', max_length=50),
        ),
    ]
