# Generated by Django 4.1.7 on 2023-03-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('temple_pictures1', models.ImageField(upload_to='media/Temples')),
                ('temple_pictures2', models.ImageField(blank=True, upload_to='media/Temples')),
                ('temple_pictures3', models.ImageField(blank=True, upload_to='media/Temples')),
                ('temple_pictures4', models.ImageField(blank=True, upload_to='media/Temples')),
            ],
            options={
                'verbose_name': 'Temples',
                'verbose_name_plural': 'Temples',
            },
        ),
    ]
