# Generated by Django 4.1.7 on 2023-03-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismPlaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplaces',
            name='place_pictures1',
            field=models.ImageField(upload_to='TourismPlaces'),
        ),
        migrations.AlterField(
            model_name='tourismplaces',
            name='place_pictures2',
            field=models.ImageField(blank=True, upload_to='TourismPlaces'),
        ),
        migrations.AlterField(
            model_name='tourismplaces',
            name='place_pictures3',
            field=models.ImageField(blank=True, upload_to='TourismPlaces'),
        ),
        migrations.AlterField(
            model_name='tourismplaces',
            name='place_pictures4',
            field=models.ImageField(blank=True, upload_to='TourismPlaces'),
        ),
    ]
