# Generated by Django 4.1.7 on 2023-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismPlaces', '0002_alter_tourismplaces_place_pictures1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismplaces',
            name='place_pictures5',
            field=models.ImageField(blank=True, upload_to='TourismPlaces'),
        ),
        migrations.AddField(
            model_name='tourismplaces',
            name='place_pictures6',
            field=models.ImageField(blank=True, upload_to='TourismPlaces'),
        ),
        migrations.AddField(
            model_name='tourismplaces',
            name='place_pictures7',
            field=models.ImageField(blank=True, upload_to='TourismPlaces'),
        ),
        migrations.AddField(
            model_name='tourismplaces',
            name='place_pictures8',
            field=models.ImageField(blank=True, upload_to='TourismPlaces'),
        ),
    ]
