# Generated by Django 4.1.7 on 2023-03-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_picture_name', models.CharField(max_length=50)),
                ('category_description', models.TextField(max_length=300)),
                ('category_picture1', models.ImageField(upload_to='media/Features')),
                ('category_picture2', models.ImageField(blank=True, upload_to='media/Features')),
            ],
            options={
                'verbose_name': 'Features',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
