# Generated by Django 4.1.7 on 2023-03-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='category_picture1',
            field=models.ImageField(upload_to='static/Features'),
        ),
        migrations.AlterField(
            model_name='features',
            name='category_picture2',
            field=models.ImageField(blank=True, upload_to='static/Features'),
        ),
    ]
